package CXGN::CDBI::Auto::SGN::Accession;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Accession - object abstraction for rows in the sgn.accession table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      accession_id

  Columns:
      accession_id
      organism_id
      common_name
      accession_name_id
      chado_organism_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.accession' );

our @primary_key_names =
    qw/
      accession_id
      /;

our @column_names =
    qw/
      accession_id
      organism_id
      common_name
      accession_name_id
      chado_organism_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
