package CXGN::CDBI::Auto::SGN::BlastHits;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::BlastHits - object abstraction for rows in the sgn.blast_hits table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      blast_hit_id

  Columns:
      blast_hit_id
      blast_annotation_id
      target_db_id
      evalue
      score
      identity_percentage
      apply_start
      apply_end
      defline_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.blast_hits' );

our @primary_key_names =
    qw/
      blast_hit_id
      /;

our @column_names =
    qw/
      blast_hit_id
      blast_annotation_id
      target_db_id
      evalue
      score
      identity_percentage
      apply_start
      apply_end
      defline_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
