package CXGN::CDBI::Auto::SGN::BlastAnnotations;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::BlastAnnotations - object abstraction for rows in the sgn.blast_annotations table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      blast_annotation_id

  Columns:
      blast_annotation_id
      apply_id
      apply_type
      blast_target_id
      n_hits
      hits_stored
      last_updated
      host
      pid

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.blast_annotations' );

our @primary_key_names =
    qw/
      blast_annotation_id
      /;

our @column_names =
    qw/
      blast_annotation_id
      apply_id
      apply_type
      blast_target_id
      n_hits
      hits_stored
      last_updated
      host
      pid
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
