package CXGN::CDBI::Auto::SGN::BlastDefline;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::BlastDefline - object abstraction for rows in the sgn.blast_defline table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      defline_id

  Columns:
      defline_id
      blast_target_id
      target_db_id
      defline
      defline_fulltext
      identifier_defline_fulltext

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.blast_defline' );

our @primary_key_names =
    qw/
      defline_id
      /;

our @column_names =
    qw/
      defline_id
      blast_target_id
      target_db_id
      defline
      defline_fulltext
      identifier_defline_fulltext
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
