package CXGN::CDBI::Auto::SGN::Cds;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Cds - object abstraction for rows in the sgn.cds table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      cds_id

  Columns:
      cds_id
      unigene_id
      seq_text
      seq_edits
      protein_seq
      begin
      end
      forward_reverse
      run_id
      score
      method
      frame
      preferred
      cds_seq
      protein_feature_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.cds' );

our @primary_key_names =
    qw/
      cds_id
      /;

our @column_names =
    qw/
      cds_id
      unigene_id
      seq_text
      seq_edits
      protein_seq
      begin
      end
      forward_reverse
      run_id
      score
      method
      frame
      preferred
      cds_seq
      protein_feature_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
