package CXGN::CDBI::Auto::SGN::Clone;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Clone - object abstraction for rows in the sgn.clone table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      clone_id

  Columns:
      clone_id
      library_id
      clone_name
      clone_group_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.clone' );

our @primary_key_names =
    qw/
      clone_id
      /;

our @column_names =
    qw/
      clone_id
      library_id
      clone_name
      clone_group_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
