package CXGN::CDBI::Auto::SGN::CommonName;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::CommonName - object abstraction for rows in the sgn.common_name table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      common_name_id

  Columns:
      common_name_id
      common_name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.common_name' );

our @primary_key_names =
    qw/
      common_name_id
      /;

our @column_names =
    qw/
      common_name_id
      common_name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
