package CXGN::CDBI::Auto::SGN::CosiiOrtholog;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::CosiiOrtholog - object abstraction for rows in the sgn.cosii_ortholog table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      cosii_unigene_id

  Columns:
      cosii_unigene_id
      marker_id
      unigene_id
      copies
      database_name
      sequence_name
      edited_sequence_id
      peptide_sequence_id
      introns

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.cosii_ortholog' );

our @primary_key_names =
    qw/
      cosii_unigene_id
      /;

our @column_names =
    qw/
      cosii_unigene_id
      marker_id
      unigene_id
      copies
      database_name
      sequence_name
      edited_sequence_id
      peptide_sequence_id
      introns
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
