package CXGN::CDBI::Auto::SGN::DeprecatedMaps;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::DeprecatedMaps - object abstraction for rows in the sgn.deprecated_maps table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      map_id

  Columns:
      map_id
      legacy_id
      short_name
      long_name
      number_chromosomes
      default_threshold
      header
      abstract
      genetic_cross
      population_type
      population_size
      seed_available
      seed_url
      deprecated_by
      map_type

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.deprecated_maps' );

our @primary_key_names =
    qw/
      map_id
      /;

our @column_names =
    qw/
      map_id
      legacy_id
      short_name
      long_name
      number_chromosomes
      default_threshold
      header
      abstract
      genetic_cross
      population_type
      population_size
      seed_available
      seed_url
      deprecated_by
      map_type
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
