package CXGN::CDBI::Auto::SGN::DeprecatedMapdata;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::DeprecatedMapdata - object abstraction for rows in the sgn.deprecated_mapdata table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      loc_id

  Columns:
      loc_id
      map_id
      lg_id
      offset
      loc_type
      loc_order

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.deprecated_mapdata' );

our @primary_key_names =
    qw/
      loc_id
      /;

our @column_names =
    qw/
      loc_id
      map_id
      lg_id
      offset
      loc_type
      loc_order
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
