package CXGN::CDBI::Auto::SGN::DeprecatedMarkerConfidences;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::DeprecatedMarkerConfidences - object abstraction for rows in the sgn.deprecated_marker_confidences table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      confidence_id

  Columns:
      confidence_id
      confidence_name
      legacy_conf_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.deprecated_marker_confidences' );

our @primary_key_names =
    qw/
      confidence_id
      /;

our @column_names =
    qw/
      confidence_id
      confidence_name
      legacy_conf_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
