package CXGN::CDBI::Auto::SGN::DeprecatedMarkerLocations;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::DeprecatedMarkerLocations - object abstraction for rows in the sgn.deprecated_marker_locations table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      marker_location_id

  Columns:
      marker_location_id
      marker_id
      loc_id
      confidence
      order_in_loc
      location_subscript
      mapmaker_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.deprecated_marker_locations' );

our @primary_key_names =
    qw/
      marker_location_id
      /;

our @column_names =
    qw/
      marker_location_id
      marker_id
      loc_id
      confidence
      order_in_loc
      location_subscript
      mapmaker_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
