package CXGN::CDBI::Auto::SGN::DeprecatedMarkerTypes;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::DeprecatedMarkerTypes - object abstraction for rows in the sgn.deprecated_marker_types table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      marker_type_id

  Columns:
      marker_type_id
      type_name
      description
      marker_table

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.deprecated_marker_types' );

our @primary_key_names =
    qw/
      marker_type_id
      /;

our @column_names =
    qw/
      marker_type_id
      type_name
      description
      marker_table
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
