package CXGN::CDBI::Auto::SGN::DomainMatch;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::DomainMatch - object abstraction for rows in the sgn.domain_match table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      domain_match_id

  Columns:
      domain_match_id
      cds_id
      unigene_id
      domain_id
      match_begin
      match_end
      e_value
      hit_status
      run_id
      metadata_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.domain_match' );

our @primary_key_names =
    qw/
      domain_match_id
      /;

our @column_names =
    qw/
      domain_match_id
      cds_id
      unigene_id
      domain_id
      match_begin
      match_end
      e_value
      hit_status
      run_id
      metadata_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
