package CXGN::CDBI::Auto::SGN::EnzymeRestrictionSites;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::EnzymeRestrictionSites - object abstraction for rows in the sgn.enzyme_restriction_sites table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      enzyme_restriction_sites_id

  Columns:
      enzyme_id
      restriction_site
      enzyme_restriction_sites_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.enzyme_restriction_sites' );

our @primary_key_names =
    qw/
      enzyme_restriction_sites_id
      /;

our @column_names =
    qw/
      enzyme_id
      restriction_site
      enzyme_restriction_sites_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
