package CXGN::CDBI::Auto::SGN::EstsMappedByClone;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::EstsMappedByClone - object abstraction for rows in the sgn.ests_mapped_by_clone table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      embc_id

  Columns:
      embc_id
      marker_id
      clone_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.ests_mapped_by_clone' );

our @primary_key_names =
    qw/
      embc_id
      /;

our @column_names =
    qw/
      embc_id
      marker_id
      clone_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
