package CXGN::CDBI::Auto::SGN::ExperimentType;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::ExperimentType - object abstraction for rows in the sgn.experiment_type table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      experiment_type_id

  Columns:
      experiment_type_id
      name
      description

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.experiment_type' );

our @primary_key_names =
    qw/
      experiment_type_id
      /;

our @column_names =
    qw/
      experiment_type_id
      name
      description
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
