package CXGN::CDBI::Auto::SGN::FamilyBuild;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::FamilyBuild - object abstraction for rows in the sgn.family_build table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      family_build_id

  Columns:
      family_build_id
      group_id
      build_nr
      i_value
      build_date
      status

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.family_build' );

our @primary_key_names =
    qw/
      family_build_id
      /;

our @column_names =
    qw/
      family_build_id
      group_id
      build_nr
      i_value
      build_date
      status
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
