package CXGN::CDBI::Auto::SGN::FamilyMember;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::FamilyMember - object abstraction for rows in the sgn.family_member table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      family_member_id

  Columns:
      family_member_id
      cds_id
      organism_group_id
      family_id
      database_name
      sequence_name
      alignment_seq

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.family_member' );

our @primary_key_names =
    qw/
      family_member_id
      /;

our @column_names =
    qw/
      family_member_id
      cds_id
      organism_group_id
      family_id
      database_name
      sequence_name
      alignment_seq
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
