package CXGN::CDBI::Auto::SGN::FishExperimenter;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::FishExperimenter - object abstraction for rows in the sgn.fish_experimenter table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      fish_experimenter_id

  Columns:
      fish_experimenter_id
      fish_experimenter_name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.fish_experimenter' );

our @primary_key_names =
    qw/
      fish_experimenter_id
      /;

our @column_names =
    qw/
      fish_experimenter_id
      fish_experimenter_name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
