package CXGN::CDBI::Auto::SGN::FishResult;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::FishResult - object abstraction for rows in the sgn.fish_result table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      fish_result_id

  Columns:
      fish_result_id
      map_id
      fish_experimenter_id
      experiment_name
      clone_id
      chromo_num
      chromo_arm
      percent_from_centromere
      experiment_group
      attribution_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.fish_result' );

our @primary_key_names =
    qw/
      fish_result_id
      /;

our @column_names =
    qw/
      fish_result_id
      map_id
      fish_experimenter_id
      experiment_name
      clone_id
      chromo_num
      chromo_arm
      percent_from_centromere
      experiment_group
      attribution_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
