package CXGN::CDBI::Auto::SGN::FishKaryotypeConstantsOld;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::FishKaryotypeConstantsOld - object abstraction for rows in the sgn.fish_karyotype_constants_old table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      chromo_num

  Columns:
      chromo_num
      chromo_length
      chromo_arm_ratio
      short_arm_length
      short_arm_eu_length
      short_arm_het_length
      long_arm_length
      long_arm_eu_length
      long_arm_het_length

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.fish_karyotype_constants_old' );

our @primary_key_names =
    qw/
      chromo_num
      /;

our @column_names =
    qw/
      chromo_num
      chromo_length
      chromo_arm_ratio
      short_arm_length
      short_arm_eu_length
      short_arm_het_length
      long_arm_length
      long_arm_eu_length
      long_arm_het_length
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
