package CXGN::CDBI::Auto::SGN::FishKaryotypeConstants;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::FishKaryotypeConstants - object abstraction for rows in the sgn.fish_karyotype_constants table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      fish_experimenter_id
      chromo_num
      chromo_arm

  Columns:
      fish_experimenter_id
      chromo_num
      chromo_arm
      arm_length
      arm_eu_length
      arm_het_length

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.fish_karyotype_constants' );

our @primary_key_names =
    qw/
      fish_experimenter_id
      chromo_num
      chromo_arm
      /;

our @column_names =
    qw/
      fish_experimenter_id
      chromo_num
      chromo_arm
      arm_length
      arm_eu_length
      arm_het_length
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
