package CXGN::CDBI::Auto::SGN::FishImage;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::FishImage - object abstraction for rows in the sgn.fish_image table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      fish_image_id

  Columns:
      fish_image_id
      filename
      fish_result_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.fish_image' );

our @primary_key_names =
    qw/
      fish_image_id
      /;

our @column_names =
    qw/
      fish_image_id
      filename
      fish_result_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
