package CXGN::CDBI::Auto::SGN::GroupLinkage;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::GroupLinkage - object abstraction for rows in the sgn.group_linkage table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      group_linkage_id

  Columns:
      group_linkage_id
      group_id
      member_id
      member_type
      member_value

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.group_linkage' );

our @primary_key_names =
    qw/
      group_linkage_id
      /;

our @column_names =
    qw/
      group_linkage_id
      group_id
      member_id
      member_type
      member_value
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
