package CXGN::CDBI::Auto::SGN::Groups;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Groups - object abstraction for rows in the sgn.groups table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      group_id

  Columns:
      group_id
      type
      comment

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.groups' );

our @primary_key_names =
    qw/
      group_id
      /;

our @column_names =
    qw/
      group_id
      type
      comment
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
