package CXGN::CDBI::Auto::SGN::IdLinkage;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::IdLinkage - object abstraction for rows in the sgn.id_linkage table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      id_linkage_id

  Columns:
      id_linkage_id
      link_id
      link_id_type
      internal_id
      internal_id_type

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.id_linkage' );

our @primary_key_names =
    qw/
      id_linkage_id
      /;

our @column_names =
    qw/
      id_linkage_id
      link_id
      link_id_type
      internal_id
      internal_id_type
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
