package CXGN::CDBI::Auto::SGN::Interpro;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Interpro - object abstraction for rows in the sgn.interpro table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      interpro_id

  Columns:
      interpro_id
      interpro_accession
      description
      description_fulltext

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.interpro' );

our @primary_key_names =
    qw/
      interpro_id
      /;

our @column_names =
    qw/
      interpro_id
      interpro_accession
      description
      description_fulltext
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
