package CXGN::CDBI::Auto::SGN::LinkageGroup;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::LinkageGroup - object abstraction for rows in the sgn.linkage_group table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      lg_id

  Columns:
      lg_id
      map_version_id
      lg_order
      lg_name
      north_location_id
      south_location_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.linkage_group' );

our @primary_key_names =
    qw/
      lg_id
      /;

our @column_names =
    qw/
      lg_id
      map_version_id
      lg_order
      lg_name
      north_location_id
      south_location_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
