package CXGN::CDBI::Auto::SGN::LocTypes;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::LocTypes - object abstraction for rows in the sgn.loc_types table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      loc_type_id

  Columns:
      loc_type_id
      type_code
      type_name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.loc_types' );

our @primary_key_names =
    qw/
      loc_type_id
      /;

our @column_names =
    qw/
      loc_type_id
      type_code
      type_name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
