package CXGN::CDBI::Auto::SGN::ManualAnnotations;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::ManualAnnotations - object abstraction for rows in the sgn.manual_annotations table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      manual_annotations_id

  Columns:
      manual_annotations_id
      annotation_target_id
      annotation_target_type_id
      annotation_text
      author_id
      date_entered
      last_modified
      annotation_text_fulltext

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.manual_annotations' );

our @primary_key_names =
    qw/
      manual_annotations_id
      /;

our @column_names =
    qw/
      manual_annotations_id
      annotation_target_id
      annotation_target_type_id
      annotation_text
      author_id
      date_entered
      last_modified
      annotation_text_fulltext
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
