package CXGN::CDBI::Auto::SGN::Map;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Map - object abstraction for rows in the sgn.map table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      map_id

  Columns:
      map_id
      short_name
      long_name
      abstract
      map_type
      parent_1
      parent_2
      units
      ancestor

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.map' );

our @primary_key_names =
    qw/
      map_id
      /;

our @column_names =
    qw/
      map_id
      short_name
      long_name
      abstract
      map_type
      parent_1
      parent_2
      units
      ancestor
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
