package CXGN::CDBI::Auto::SGN::MarkerLocation;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::MarkerLocation - object abstraction for rows in the sgn.marker_location table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      location_id

  Columns:
      location_id
      lg_id
      map_version_id
      position
      confidence_id
      subscript

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.marker_location' );

our @primary_key_names =
    qw/
      location_id
      /;

our @column_names =
    qw/
      location_id
      lg_id
      map_version_id
      position
      confidence_id
      subscript
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
