package CXGN::CDBI::Auto::SGN::MarkerCollectible;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::MarkerCollectible - object abstraction for rows in the sgn.marker_collectible table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      marker_collectible_dummy_id

  Columns:
      marker_collectible_dummy_id
      marker_id
      mc_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.marker_collectible' );

our @primary_key_names =
    qw/
      marker_collectible_dummy_id
      /;

our @column_names =
    qw/
      marker_collectible_dummy_id
      marker_id
      mc_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
