package CXGN::CDBI::Auto::SGN::MarkerCollection;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::MarkerCollection - object abstraction for rows in the sgn.marker_collection table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      mc_id

  Columns:
      mc_id
      mc_name
      mc_description

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.marker_collection' );

our @primary_key_names =
    qw/
      mc_id
      /;

our @column_names =
    qw/
      mc_id
      mc_name
      mc_description
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
