package CXGN::CDBI::Auto::SGN::Marker;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Marker - object abstraction for rows in the sgn.marker table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      marker_id

  Columns:
      marker_id
      dummy_field

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.marker' );

our @primary_key_names =
    qw/
      marker_id
      /;

our @column_names =
    qw/
      marker_id
      dummy_field
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
