package CXGN::CDBI::Auto::SGN::MarkerToMap;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::MarkerToMap - object abstraction for rows in the sgn.marker_to_map table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:


  Columns:
      marker_id
      protocol
      location_id
      lg_name
      lg_order
      position
      confidence_id
      subscript
      map_version_id
      map_id
      parent_1
      parent_2
      current_version

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.marker_to_map' );

our @primary_key_names =
    qw/

      /;

our @column_names =
    qw/
      marker_id
      protocol
      location_id
      lg_name
      lg_order
      position
      confidence_id
      subscript
      map_version_id
      map_id
      parent_1
      parent_2
      current_version
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
