package CXGN::CDBI::Auto::SGN::MarkerAlias;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::MarkerAlias - object abstraction for rows in the sgn.marker_alias table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      alias_id

  Columns:
      alias_id
      alias
      marker_id
      preferred

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.marker_alias' );

our @primary_key_names =
    qw/
      alias_id
      /;

our @column_names =
    qw/
      alias_id
      alias
      marker_id
      preferred
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
