package CXGN::CDBI::Auto::SGN::Metadata;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Metadata - object abstraction for rows in the sgn.metadata table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      metadata_id

  Columns:
      metadata_id
      create_date
      create_person_id
      modified_date
      modified_person_id
      previous_metadata_id
      obsolete
      obsolete_note

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.metadata' );

our @primary_key_names =
    qw/
      metadata_id
      /;

our @column_names =
    qw/
      metadata_id
      create_date
      create_person_id
      modified_date
      modified_person_id
      previous_metadata_id
      obsolete
      obsolete_note
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
