package CXGN::CDBI::Auto::SGN::Microarray;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Microarray - object abstraction for rows in the sgn.microarray table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      microarray_id

  Columns:
      microarray_id
      chip_name
      release
      version
      spot_id
      content_specific_tag
      clone_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.microarray' );

our @primary_key_names =
    qw/
      microarray_id
      /;

our @column_names =
    qw/
      microarray_id
      chip_name
      release
      version
      spot_id
      content_specific_tag
      clone_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
