package CXGN::CDBI::Auto::SGN::Organismprop;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Organismprop - object abstraction for rows in the sgn.organismprop table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      organismprop_id

  Columns:
      organismprop_id
      common_name_id
      type_id
      value
      rank

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.organismprop' );

our @primary_key_names =
    qw/
      organismprop_id
      /;

our @column_names =
    qw/
      organismprop_id
      common_name_id
      type_id
      value
      rank
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
