package CXGN::CDBI::Auto::SGN::Organism;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Organism - object abstraction for rows in the sgn.organism table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      organism_id

  Columns:
      organism_id
      organism_name
      common_name_id
      organism_descrip
      specie_tax
      genus_tax
      subfamily_tax
      family_tax
      order_tax
      chr_n_gnmc
      polypl_gnmc
      genom_size_gnmc
      genom_proj_gnmc
      est_attribution_tqmc
      chado_organism_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.organism' );

our @primary_key_names =
    qw/
      organism_id
      /;

our @column_names =
    qw/
      organism_id
      organism_name
      common_name_id
      organism_descrip
      specie_tax
      genus_tax
      subfamily_tax
      family_tax
      order_tax
      chr_n_gnmc
      polypl_gnmc
      genom_size_gnmc
      genom_proj_gnmc
      est_attribution_tqmc
      chado_organism_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
