package CXGN::CDBI::Auto::SGN::PrimerUnigeneMatch;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::PrimerUnigeneMatch - object abstraction for rows in the sgn.primer_unigene_match table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      primer_unigene_match_id

  Columns:
      primer_unigene_match_id
      marker_id
      unigene_id
      primer_direction
      match_length
      primer_match_start
      primer_match_end
      unigene_match_start
      unigene_match_end
      e_value

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.primer_unigene_match' );

our @primary_key_names =
    qw/
      primer_unigene_match_id
      /;

our @column_names =
    qw/
      primer_unigene_match_id
      marker_id
      unigene_id
      primer_direction
      match_length
      primer_match_start
      primer_match_end
      unigene_match_start
      unigene_match_end
      e_value
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
