package CXGN::CDBI::Auto::SGN::RflpMarkers;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::RflpMarkers - object abstraction for rows in the sgn.rflp_markers table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      rflp_id

  Columns:
      rflp_id
      marker_id
      rflp_name
      library_name
      clone_name
      vector
      cutting_site
      forward_seq_id
      reverse_seq_id
      insert_size
      drug_resistance
      marker_prefix
      marker_suffix

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.rflp_markers' );

our @primary_key_names =
    qw/
      rflp_id
      /;

our @column_names =
    qw/
      rflp_id
      marker_id
      rflp_name
      library_name
      clone_name
      vector
      cutting_site
      forward_seq_id
      reverse_seq_id
      insert_size
      drug_resistance
      marker_prefix
      marker_suffix
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
