package CXGN::CDBI::Auto::SGN::RflpSequences;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::RflpSequences - object abstraction for rows in the sgn.rflp_sequences table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      seq_id

  Columns:
      seq_id
      fasta_sequence

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.rflp_sequences' );

our @primary_key_names =
    qw/
      seq_id
      /;

our @column_names =
    qw/
      seq_id
      fasta_sequence
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
