package CXGN::CDBI::Auto::SGN::RflpUnigeneAssociations;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::RflpUnigeneAssociations - object abstraction for rows in the sgn.rflp_unigene_associations table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      rflp_unigene_assoc_id

  Columns:
      rflp_unigene_assoc_id
      rflp_seq_id
      unigene_id
      e_val
      align_length
      query_start
      query_end

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.rflp_unigene_associations' );

our @primary_key_names =
    qw/
      rflp_unigene_assoc_id
      /;

our @column_names =
    qw/
      rflp_unigene_assoc_id
      rflp_seq_id
      unigene_id
      e_val
      align_length
      query_start
      query_end
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
