package CXGN::CDBI::Auto::SGN::Seqread;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Seqread - object abstraction for rows in the sgn.seqread table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      read_id

  Columns:
      read_id
      clone_id
      facility_id
      submitter_id
      batch_id
      primer
      direction
      trace_name
      trace_location
      attribution_id
      date
      censor_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.seqread' );

our @primary_key_names =
    qw/
      read_id
      /;

our @column_names =
    qw/
      read_id
      clone_id
      facility_id
      submitter_id
      batch_id
      primer
      direction
      trace_name
      trace_location
      attribution_id
      date
      censor_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
