package CXGN::CDBI::Auto::SGN::Sequence;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Sequence - object abstraction for rows in the sgn.sequence table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      sequence_id

  Columns:
      sequence_id
      sequence

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.sequence' );

our @primary_key_names =
    qw/
      sequence_id
      /;

our @column_names =
    qw/
      sequence_id
      sequence
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
