package CXGN::CDBI::Auto::SGN::Ssr;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Ssr - object abstraction for rows in the sgn.ssr table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      ssr_id

  Columns:
      ssr_id
      marker_id
      ssr_name
      est_read_id
      start_primer
      end_primer
      pcr_product_ln
      tm_start_primer
      tm_end_primer
      ann_high
      ann_low

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.ssr' );

our @primary_key_names =
    qw/
      ssr_id
      /;

our @column_names =
    qw/
      ssr_id
      marker_id
      ssr_name
      est_read_id
      start_primer
      end_primer
      pcr_product_ln
      tm_start_primer
      tm_end_primer
      ann_high
      ann_low
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
