package CXGN::CDBI::Auto::SGN::Taxonomy;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Taxonomy - object abstraction for rows in the sgn.taxonomy table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      tax_id

  Columns:
      tax_id
      tax_name
      tax_type

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.taxonomy' );

our @primary_key_names =
    qw/
      tax_id
      /;

our @column_names =
    qw/
      tax_id
      tax_name
      tax_type
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
