package CXGN::CDBI::Auto::SGN::TempMarkerCorrespondence;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::TempMarkerCorrespondence - object abstraction for rows in the sgn.temp_marker_correspondence table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      tmc_id

  Columns:
      tmc_id
      old_marker_id
      new_marker_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.temp_marker_correspondence' );

our @primary_key_names =
    qw/
      tmc_id
      /;

our @column_names =
    qw/
      tmc_id
      old_marker_id
      new_marker_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
