package CXGN::CDBI::Auto::SGN::TigrtcIndex;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::TigrtcIndex - object abstraction for rows in the sgn.tigrtc_index table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      tcindex_id

  Columns:
      tcindex_id
      index_name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.tigrtc_index' );

our @primary_key_names =
    qw/
      tcindex_id
      /;

our @column_names =
    qw/
      tcindex_id
      index_name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
