package CXGN::CDBI::Auto::SGN::TigrtcTracking;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::TigrtcTracking - object abstraction for rows in the sgn.tigrtc_tracking table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      tigrtc_tracking_id

  Columns:
      tigrtc_tracking_id
      tc_id
      current_tc_id
      tcindex_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.tigrtc_tracking' );

our @primary_key_names =
    qw/
      tigrtc_tracking_id
      /;

our @column_names =
    qw/
      tigrtc_tracking_id
      tc_id
      current_tc_id
      tcindex_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
