package CXGN::CDBI::Auto::SGN::TmMarkersSequences;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::TmMarkersSequences - object abstraction for rows in the sgn.tm_markers_sequences table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      tm_marker_seq_id

  Columns:
      tm_marker_seq_id
      tm_id
      sequence
      comment

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.tm_markers_sequences' );

our @primary_key_names =
    qw/
      tm_marker_seq_id
      /;

our @column_names =
    qw/
      tm_marker_seq_id
      tm_id
      sequence
      comment
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
