package CXGN::CDBI::Auto::SGN::TmMarkers;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::TmMarkers - object abstraction for rows in the sgn.tm_markers table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      tm_id

  Columns:
      tm_id
      marker_id
      tm_name
      old_cos_id
      seq_id
      est_read_id
      comment

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.tm_markers' );

our @primary_key_names =
    qw/
      tm_id
      /;

our @column_names =
    qw/
      tm_id
      marker_id
      tm_name
      old_cos_id
      seq_id
      est_read_id
      comment
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
