package CXGN::CDBI::Auto::SGN::TrimFeatureTypes;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::TrimFeatureTypes - object abstraction for rows in the sgn.trim_feature_types table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      trim_type_id

  Columns:
      trim_type_id
      comment

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.trim_feature_types' );

our @primary_key_names =
    qw/
      trim_type_id
      /;

our @column_names =
    qw/
      trim_type_id
      comment
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
