package CXGN::CDBI::Auto::SGN::TrimFeature;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::TrimFeature - object abstraction for rows in the sgn.trim_feature table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      feature_id

  Columns:
      feature_id
      est_id
      start
      end
      type
      value

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.trim_feature' );

our @primary_key_names =
    qw/
      feature_id
      /;

our @column_names =
    qw/
      feature_id
      est_id
      start
      end
      type
      value
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
