package CXGN::CDBI::Auto::SGN::Types;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Types - object abstraction for rows in the sgn.types table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      type_id

  Columns:
      type_id
      comment

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.types' );

our @primary_key_names =
    qw/
      type_id
      /;

our @column_names =
    qw/
      type_id
      comment
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
