package CXGN::CDBI::Auto::SGN::UnigeneMember;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::UnigeneMember - object abstraction for rows in the sgn.unigene_member table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      unigene_member_id

  Columns:
      unigene_member_id
      unigene_id
      est_id
      start
      stop
      qstart
      qend
      dir

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.unigene_member' );

our @primary_key_names =
    qw/
      unigene_member_id
      /;

our @column_names =
    qw/
      unigene_member_id
      unigene_id
      est_id
      start
      stop
      qstart
      qend
      dir
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
