package CXGN::CDBI::Auto::SGN::Unigene;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGN::Unigene - object abstraction for rows in the sgn.unigene table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      unigene_id

  Columns:
      unigene_id
      unigene_build_id
      consensi_id
      cluster_no
      contig_no
      nr_members
      database_name
      sequence_name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn.unigene' );

our @primary_key_names =
    qw/
      unigene_id
      /;

our @column_names =
    qw/
      unigene_id
      unigene_build_id
      consensi_id
      cluster_no
      contig_no
      nr_members
      database_name
      sequence_name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
