package CXGN::CDBI::Auto::SGNSubmit::Facility;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNSubmit::Facility - object abstraction for rows in the sgn_submit.facility table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      facility_id

  Columns:
      facility_id
      submit_user_id
      facility_moniker
      facility_shortname
      facility_name
      facility_contact
      facility_address
      funding_agency
      funding_comment
      sequencing_primers
      machine
      chemistry
      attribution_display
      sp_person_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_submit.facility' );

our @primary_key_names =
    qw/
      facility_id
      /;

our @column_names =
    qw/
      facility_id
      submit_user_id
      facility_moniker
      facility_shortname
      facility_name
      facility_contact
      facility_address
      funding_agency
      funding_comment
      sequencing_primers
      machine
      chemistry
      attribution_display
      sp_person_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
