package CXGN::CDBI::Auto::SGNSubmit::Seqread;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNSubmit::Seqread - object abstraction for rows in the sgn_submit.seqread table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      submit_read_id

  Columns:
      submit_read_id
      library_id
      facility_id
      trace_name
      clone_name
      direction
      location
      read_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_submit.seqread' );

our @primary_key_names =
    qw/
      submit_read_id
      /;

our @column_names =
    qw/
      submit_read_id
      library_id
      facility_id
      trace_name
      clone_name
      direction
      location
      read_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
