package CXGN::CDBI::Auto::SGNSubmit::SubmitUser;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNSubmit::SubmitUser - object abstraction for rows in the sgn_submit.submit_user table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      submit_user_id

  Columns:
      submit_user_id
      submit_code
      username
      password
      name
      email_address
      phone_number
      organization
      contact_information
      disabled
      confirm_code
      sp_person_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_submit.submit_user' );

our @primary_key_names =
    qw/
      submit_user_id
      /;

our @column_names =
    qw/
      submit_user_id
      submit_code
      username
      password
      name
      email_address
      phone_number
      organization
      contact_information
      disabled
      confirm_code
      sp_person_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
