package CXGN::CDBI::Auto::TomatoGFF::Fattribute;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::TomatoGFF::Fattribute - object abstraction for rows in the tomato_gff.fattribute table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      fattribute_id

  Columns:
      fattribute_id
      fattribute_name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'tomato_gff.fattribute' );

our @primary_key_names =
    qw/
      fattribute_id
      /;

our @column_names =
    qw/
      fattribute_id
      fattribute_name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
