package CXGN::CDBI::Auto::TomatoGFF::FattributeToFeature;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::TomatoGFF::FattributeToFeature - object abstraction for rows in the tomato_gff.fattribute_to_feature table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:


  Columns:
      fid
      fattribute_id
      fattribute_value

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'tomato_gff.fattribute_to_feature' );

our @primary_key_names =
    qw/

      /;

our @column_names =
    qw/
      fid
      fattribute_id
      fattribute_value
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
