package CXGN::CDBI::Auto::TomatoGFF::Fdata;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::TomatoGFF::Fdata - object abstraction for rows in the tomato_gff.fdata table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      fid

  Columns:
      fid
      fref
      fstart
      fstop
      fbin
      ftypeid
      fscore
      fstrand
      fphase
      gid
      ftarget_start
      ftarget_stop

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'tomato_gff.fdata' );

our @primary_key_names =
    qw/
      fid
      /;

our @column_names =
    qw/
      fid
      fref
      fstart
      fstop
      fbin
      ftypeid
      fscore
      fstrand
      fphase
      gid
      ftarget_start
      ftarget_stop
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
