package CXGN::CDBI::Auto::Metadata::AttributionTo;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Metadata::AttributionTo - object abstraction for rows in the metadata.attribution_to table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      attribution_to_id

  Columns:
      attribution_to_id
      attribution_id
      person_id
      organization_id
      project_id
      role_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'metadata.attribution_to' );

our @primary_key_names =
    qw/
      attribution_to_id
      /;

our @column_names =
    qw/
      attribution_to_id
      attribution_id
      person_id
      organization_id
      project_id
      role_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
