package CXGN::CDBI::Auto::Metadata::Comments;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Metadata::Comments - object abstraction for rows in the metadata.comments table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      comment_id

  Columns:
      comment_id
      attribution_id
      comment_text

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'metadata.comments' );

our @primary_key_names =
    qw/
      comment_id
      /;

our @column_names =
    qw/
      comment_id
      attribution_id
      comment_text
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
