package CXGN::CDBI::Auto::Metadata::Roles;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Metadata::Roles - object abstraction for rows in the metadata.roles table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      role_id

  Columns:
      role_id
      role_name
      role_description

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'metadata.roles' );

our @primary_key_names =
    qw/
      role_id
      /;

our @column_names =
    qw/
      role_id
      role_name
      role_description
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
