package CXGN::CDBI::Auto::Physical::BacConsensusSequences;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::BacConsensusSequences - object abstraction for rows in the physical.bac_consensus_sequences table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      consensus_seq_id

  Columns:
      consensus_seq_id
      fasta_sequence
      bac_id
      tracefile
      consensus_seq_name
      length
      includes_sp6_end
      includes_t7_end

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.bac_consensus_sequences' );

our @primary_key_names =
    qw/
      consensus_seq_id
      /;

our @column_names =
    qw/
      consensus_seq_id
      fasta_sequence
      bac_id
      tracefile
      consensus_seq_name
      length
      includes_sp6_end
      includes_t7_end
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
