package CXGN::CDBI::Auto::Physical::BacEndSequences;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::BacEndSequences - object abstraction for rows in the physical.bac_end_sequences table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      end_seq_id

  Columns:
      end_seq_id
      end_id
      fasta_sequence
      tracefile
      length

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.bac_end_sequences' );

our @primary_key_names =
    qw/
      end_seq_id
      /;

our @column_names =
    qw/
      end_seq_id
      end_id
      fasta_sequence
      tracefile
      length
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
