package CXGN::CDBI::Auto::Physical::Bacs;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::Bacs - object abstraction for rows in the physical.bacs table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      bac_id

  Columns:
      bac_id
      cornell_clone_name
      arizona_clone_name
      species_id
      sp6_end_seq_id
      t7_end_seq_id
      genbank_accession
      bad_clone
      estimated_length
      library_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.bacs' );

our @primary_key_names =
    qw/
      bac_id
      /;

our @column_names =
    qw/
      bac_id
      cornell_clone_name
      arizona_clone_name
      species_id
      sp6_end_seq_id
      t7_end_seq_id
      genbank_accession
      bad_clone
      estimated_length
      library_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
