package CXGN::CDBI::Auto::Physical::ComputationalAssociations;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::ComputationalAssociations - object abstraction for rows in the physical.computational_associations table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      computational_assoc_id

  Columns:
      computational_assoc_id
      marker_id
      clone_id
      e_value
      q_start
      q_end
      s_start
      s_end
      identity
      score
      parameters

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.computational_associations' );

our @primary_key_names =
    qw/
      computational_assoc_id
      /;

our @column_names =
    qw/
      computational_assoc_id
      marker_id
      clone_id
      e_value
      q_start
      q_end
      s_start
      s_end
      identity
      score
      parameters
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
