package CXGN::CDBI::Auto::Physical::ContigSizes;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::ContigSizes - object abstraction for rows in the physical.contig_sizes table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      contig_size_id

  Columns:
      contig_size_id
      bac_contig_id
      contig_size

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.contig_sizes' );

our @primary_key_names =
    qw/
      contig_size_id
      /;

our @column_names =
    qw/
      contig_size_id
      bac_contig_id
      contig_size
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
