package CXGN::CDBI::Auto::Physical::ManualAssociations;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::ManualAssociations - object abstraction for rows in the physical.manual_associations table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      manual_assoc_id

  Columns:
      manual_assoc_id
      marker_id
      clone_id
      pubmed_id
      sp_person_id
      comment

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.manual_associations' );

our @primary_key_names =
    qw/
      manual_assoc_id
      /;

our @column_names =
    qw/
      manual_assoc_id
      marker_id
      clone_id
      pubmed_id
      sp_person_id
      comment
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
