package CXGN::CDBI::Auto::Physical::OvergoPlates;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::OvergoPlates - object abstraction for rows in the physical.overgo_plates table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      plate_id

  Columns:
      plate_id
      plate_number
      row_max
      col_max
      plate_size
      empty_wells

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.overgo_plates' );

our @primary_key_names =
    qw/
      plate_id
      /;

our @column_names =
    qw/
      plate_id
      plate_number
      row_max
      col_max
      plate_size
      empty_wells
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
