package CXGN::CDBI::Auto::Physical::OvergoResults;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::OvergoResults - object abstraction for rows in the physical.overgo_results table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      result_id

  Columns:
      result_id
      overgo_plate_id
      overgo_pool
      bac_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.overgo_results' );

our @primary_key_names =
    qw/
      result_id
      /;

our @column_names =
    qw/
      result_id
      overgo_plate_id
      overgo_pool
      bac_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
