package CXGN::CDBI::Auto::Physical::PlausibleBacsInAllContigs;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::PlausibleBacsInAllContigs - object abstraction for rows in the physical.plausible_bacs_in_all_contigs table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:


  Columns:
      overgo_assoc_id
      overgo_version
      overgo_probe_id
      bac_id
      overgo_plausible
      overgo_map
      bac_assoc_id
      bac_contig_id
      contig_name
      fpc_version
      bac_plausible
      bac_map

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.plausible_bacs_in_all_contigs' );

our @primary_key_names =
    qw/

      /;

our @column_names =
    qw/
      overgo_assoc_id
      overgo_version
      overgo_probe_id
      bac_id
      overgo_plausible
      overgo_map
      bac_assoc_id
      bac_contig_id
      contig_name
      fpc_version
      bac_plausible
      bac_map
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
