package CXGN::CDBI::Auto::Physical::ProbeMarkers;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::ProbeMarkers - object abstraction for rows in the physical.probe_markers table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      overgo_probe_id

  Columns:
      overgo_probe_id
      overgo_plate_id
      overgo_plate_row
      overgo_plate_col
      marker_id
      overgo_seq_a
      overgo_seq_b
      overgo_seq_ab
      marker_seq

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.probe_markers' );

our @primary_key_names =
    qw/
      overgo_probe_id
      /;

our @column_names =
    qw/
      overgo_probe_id
      overgo_plate_id
      overgo_plate_row
      overgo_plate_col
      marker_id
      overgo_seq_a
      overgo_seq_b
      overgo_seq_ab
      marker_seq
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
