package CXGN::CDBI::Auto::Physical::Species;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::Species - object abstraction for rows in the physical.species table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      species_id

  Columns:
      species_id
      short_name
      long_name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.species' );

our @primary_key_names =
    qw/
      species_id
      /;

our @column_names =
    qw/
      species_id
      short_name
      long_name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
