package CXGN::CDBI::Auto::Physical::Users;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Physical::Users - object abstraction for rows in the physical.users table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      user_id

  Columns:
      user_id
      full_name
      net_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'physical.users' );

our @primary_key_names =
    qw/
      user_id
      /;

our @column_names =
    qw/
      user_id
      full_name
      net_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
