package CXGN::CDBI::Auto::Genomic::BlastHit;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::BlastHit - object abstraction for rows in the genomic.blast_hit table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      blast_hit_id

  Columns:
      blast_hit_id
      blast_query_id
      identifier
      evalue
      score
      identity_percentage
      align_start
      align_end
      blast_defline_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.blast_hit' );

our @primary_key_names =
    qw/
      blast_hit_id
      /;

our @column_names =
    qw/
      blast_hit_id
      blast_query_id
      identifier
      evalue
      score
      identity_percentage
      align_start
      align_end
      blast_defline_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
