package CXGN::CDBI::Auto::Genomic::BlastDefline;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::BlastDefline - object abstraction for rows in the genomic.blast_defline table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      blast_defline_id

  Columns:
      blast_defline_id
      blast_db_id
      identifier
      defline
      identifier_defline_fulltext

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.blast_defline' );

our @primary_key_names =
    qw/
      blast_defline_id
      /;

our @column_names =
    qw/
      blast_defline_id
      blast_db_id
      identifier
      defline
      identifier_defline_fulltext
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
