package CXGN::CDBI::Auto::Genomic::BlastQuery;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::BlastQuery - object abstraction for rows in the genomic.blast_query table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      blast_query_id

  Columns:
      blast_query_id
      source_id
      query_source_type_id
      blast_db_id
      total_hits
      stored_hits
      last_updated

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.blast_query' );

our @primary_key_names =
    qw/
      blast_query_id
      /;

our @column_names =
    qw/
      blast_query_id
      source_id
      query_source_type_id
      blast_db_id
      total_hits
      stored_hits
      last_updated
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
