package CXGN::CDBI::Auto::Genomic::Chromat;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::Chromat - object abstraction for rows in the genomic.chromat table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      chromat_id

  Columns:
      chromat_id
      clone_id
      primer
      direction
      filename
      subpath
      date
      censor_id
      read_class_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.chromat' );

our @primary_key_names =
    qw/
      chromat_id
      /;

our @column_names =
    qw/
      chromat_id
      clone_id
      primer
      direction
      filename
      subpath
      date
      censor_id
      read_class_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
