package CXGN::CDBI::Auto::Genomic::Clone;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::Clone - object abstraction for rows in the genomic.clone table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      clone_id

  Columns:
      clone_id
      library_id
      clone_type_id
      platenum
      wellrow
      wellcol
      genbank_accession
      bad_clone
      estimated_length

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.clone' );

our @primary_key_names =
    qw/
      clone_id
      /;

our @column_names =
    qw/
      clone_id
      library_id
      clone_type_id
      platenum
      wellrow
      wellcol
      genbank_accession
      bad_clone
      estimated_length
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
