package CXGN::CDBI::Auto::Genomic::CloneType;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::CloneType - object abstraction for rows in the genomic.clone_type table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      clone_type_id

  Columns:
      clone_type_id
      name
      shortname

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.clone_type' );

our @primary_key_names =
    qw/
      clone_type_id
      /;

our @column_names =
    qw/
      clone_type_id
      name
      shortname
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
