package CXGN::CDBI::Auto::Genomic::GenbankSubmission;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::GenbankSubmission - object abstraction for rows in the genomic.genbank_submission table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      genbank_submission_id

  Columns:
      genbank_submission_id
      date_generated
      date_sent
      submitted_by
      ncbi_reply_date

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.genbank_submission' );

our @primary_key_names =
    qw/
      genbank_submission_id
      /;

our @column_names =
    qw/
      genbank_submission_id
      date_generated
      date_sent
      submitted_by
      ncbi_reply_date
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
