package CXGN::CDBI::Auto::Genomic::Gss;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::Gss - object abstraction for rows in the genomic.gss table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      gss_id

  Columns:
      gss_id
      chromat_id
      version
      basecaller
      seq
      qual
      call_positions
      status
      flags
      date

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.gss' );

our @primary_key_names =
    qw/
      gss_id
      /;

our @column_names =
    qw/
      gss_id
      chromat_id
      version
      basecaller
      seq
      qual
      call_positions
      status
      flags
      date
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
