package CXGN::CDBI::Auto::Genomic::GssSubmittedToGenbank;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::GssSubmittedToGenbank - object abstraction for rows in the genomic.gss_submitted_to_genbank table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      gss_submitted_to_genbank_id

  Columns:
      gss_submitted_to_genbank_id
      genbank_submission_id
      gss_id
      genbank_identifier
      genbank_dbgss_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.gss_submitted_to_genbank' );

our @primary_key_names =
    qw/
      gss_submitted_to_genbank_id
      /;

our @column_names =
    qw/
      gss_submitted_to_genbank_id
      genbank_submission_id
      gss_id
      genbank_identifier
      genbank_dbgss_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
