package CXGN::CDBI::Auto::Genomic::LibraryShortnameAbbreviation;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::LibraryShortnameAbbreviation - object abstraction for rows in the genomic.library_shortname_abbreviation table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      library_shortname_abbreviation_id

  Columns:
      library_shortname_abbreviation_id
      library_id
      abbreviation

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.library_shortname_abbreviation' );

our @primary_key_names =
    qw/
      library_shortname_abbreviation_id
      /;

our @column_names =
    qw/
      library_shortname_abbreviation_id
      library_id
      abbreviation
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
