package CXGN::CDBI::Auto::Genomic::Library;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::Library - object abstraction for rows in the genomic.library table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      library_id

  Columns:
      library_id
      clone_type_id
      name
      shortname
      library_detail_id
      accession_id
      subclone_of
      cloning_host
      rs1
      rs2
      vector_ligation_1
      vector_ligation_2
      vector
      left_primer_id
      right_primer_id
      organism_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.library' );

our @primary_key_names =
    qw/
      library_id
      /;

our @column_names =
    qw/
      library_id
      clone_type_id
      name
      shortname
      library_detail_id
      accession_id
      subclone_of
      cloning_host
      rs1
      rs2
      vector_ligation_1
      vector_ligation_2
      vector
      left_primer_id
      right_primer_id
      organism_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
