package CXGN::CDBI::Auto::Genomic::LibraryDetail;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::LibraryDetail - object abstraction for rows in the genomic.library_detail table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      library_detail_id

  Columns:
      library_detail_id
      cloning_host
      vector
      rs1
      rs2
      cloning_kit
      comments
      vector_ligation_1
      vector_ligation_2

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.library_detail' );

our @primary_key_names =
    qw/
      library_detail_id
      /;

our @column_names =
    qw/
      library_detail_id
      cloning_host
      vector
      rs1
      rs2
      cloning_kit
      comments
      vector_ligation_1
      vector_ligation_2
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
