package CXGN::CDBI::Auto::Genomic::ReadClass;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::ReadClass - object abstraction for rows in the genomic.read_class table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      read_class_id

  Columns:
      read_class_id
      class_name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.read_class' );

our @primary_key_names =
    qw/
      read_class_id
      /;

our @column_names =
    qw/
      read_class_id
      class_name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
