package CXGN::CDBI::Auto::Genomic::SequencingPrimer;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Genomic::SequencingPrimer - object abstraction for rows in the genomic.sequencing_primer table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      sequencing_primer_id

  Columns:
      sequencing_primer_id
      name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'genomic.sequencing_primer' );

our @primary_key_names =
    qw/
      sequencing_primer_id
      /;

our @column_names =
    qw/
      sequencing_primer_id
      name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
