package CXGN::CDBI::Auto::Annotation::Comment;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::Comment - object abstraction for rows in the annotation.comment table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      comment_id

  Columns:
      comment_id
      text
      person_id
      date
      table_name
      table_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.comment' );

our @primary_key_names =
    qw/
      comment_id
      /;

our @column_names =
    qw/
      comment_id
      text
      person_id
      date
      table_name
      table_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
