package CXGN::CDBI::Auto::Annotation::Dbxref;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::Dbxref - object abstraction for rows in the annotation.dbxref table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      dbxref_id

  Columns:
      dbxref_id
      db_id
      db_key
      table_name
      table_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.dbxref' );

our @primary_key_names =
    qw/
      dbxref_id
      /;

our @column_names =
    qw/
      dbxref_id
      db_id
      db_key
      table_name
      table_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
