package CXGN::CDBI::Auto::Annotation::FeatureSet;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::FeatureSet - object abstraction for rows in the annotation.feature_set table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      f_set_id

  Columns:
      f_set_id
      annot_id
      name
      type
      cdna_seq_id
      cds_seq_id
      prot_seq_id
      description
      date
      person_id
      timestamp
      version
      history_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.feature_set' );

our @primary_key_names =
    qw/
      f_set_id
      /;

our @column_names =
    qw/
      f_set_id
      annot_id
      name
      type
      cdna_seq_id
      cds_seq_id
      prot_seq_id
      description
      date
      person_id
      timestamp
      version
      history_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
