package CXGN::CDBI::Auto::Annotation::Output;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::Output - object abstraction for rows in the annotation.output table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      output_id

  Columns:
      output_id
      r_span_id
      type
      value

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.output' );

our @primary_key_names =
    qw/
      output_id
      /;

our @column_names =
    qw/
      output_id
      r_span_id
      type
      value
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
