package CXGN::CDBI::Auto::Annotation::Program;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::Program - object abstraction for rows in the annotation.program table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      program_id

  Columns:
      program_id
      name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.program' );

our @primary_key_names =
    qw/
      program_id
      /;

our @column_names =
    qw/
      program_id
      name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
