package CXGN::CDBI::Auto::Annotation::ResultSpan;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::ResultSpan - object abstraction for rows in the annotation.result_span table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      r_span_id

  Columns:
      r_span_id
      r_set_id
      type
      score
      output_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.result_span' );

our @primary_key_names =
    qw/
      r_span_id
      /;

our @column_names =
    qw/
      r_span_id
      r_set_id
      type
      score
      output_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
