package CXGN::CDBI::Auto::Annotation::ResultSet;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::ResultSet - object abstraction for rows in the annotation.result_set table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      r_set_id

  Columns:
      r_set_id
      ca_id
      name
      timestamp

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.result_set' );

our @primary_key_names =
    qw/
      r_set_id
      /;

our @column_names =
    qw/
      r_set_id
      ca_id
      name
      timestamp
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
