package CXGN::CDBI::Auto::Annotation::Seq;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::Seq - object abstraction for rows in the annotation.seq table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      seq_id

  Columns:
      seq_id
      id
      version
      length
      md5checksum
      name
      description
      organism_id
      type
      residues
      genbank_gi
      person_id
      clone_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.seq' );

our @primary_key_names =
    qw/
      seq_id
      /;

our @column_names =
    qw/
      seq_id
      id
      version
      length
      md5checksum
      name
      description
      organism_id
      type
      residues
      genbank_gi
      person_id
      clone_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
