package CXGN::CDBI::Auto::Annotation::SeqError;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::SeqError - object abstraction for rows in the annotation.seq_error table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      seq_err_id

  Columns:
      seq_err_id
      seq_id
      type
      position

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.seq_error' );

our @primary_key_names =
    qw/
      seq_err_id
      /;

our @column_names =
    qw/
      seq_err_id
      seq_id
      type
      position
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
