package CXGN::CDBI::Auto::Annotation::SeqRelationship;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::SeqRelationship - object abstraction for rows in the annotation.seq_relationship table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      seq_rel_id

  Columns:
      seq_rel_id
      seq_id
      type
      alignment
      start
      end
      strand
      table_name
      table_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.seq_relationship' );

our @primary_key_names =
    qw/
      seq_rel_id
      /;

our @column_names =
    qw/
      seq_rel_id
      seq_id
      type
      alignment
      start
      end
      strand
      table_name
      table_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
