package CXGN::CDBI::Auto::Annotation::Synonym;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Annotation::Synonym - object abstraction for rows in the annotation.synonym table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      synonym_id

  Columns:
      synonym_id
      name
      table_name
      table_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'annotation.synonym' );

our @primary_key_names =
    qw/
      synonym_id
      /;

our @column_names =
    qw/
      synonym_id
      name
      table_name
      table_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
