package CXGN::CDBI::SGN::Groups;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::SGN::Groups - object abstraction for rows in the sgn.groups table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      group_id

  Columns:
      group_id
      type
      comment

  Sequence:
      (sgn base schema).groups_group_id_seq

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table(__PACKAGE__->qualify_schema('sgn') . '.groups');

our @primary_key_names =
    qw/
      group_id
      /;

our @column_names =
    qw/
      group_id
      type
      comment
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );
__PACKAGE__->sequence( __PACKAGE__->base_schema('sgn').'.groups_group_id_seq' );

=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
