package CXGN::CDBI::Auto::SGNPeople::CloneIlMappingBinLog;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::CloneIlMappingBinLog - object abstraction for rows in the sgn_people.clone_il_mapping_bin_log table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      sp_clone_il_mapping_bin_log_id

  Columns:
      sp_clone_il_mapping_bin_log_id
      genotype_region_id
      sp_person_id
      clone_id
      is_current
      created
      chromosome
      notes

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.clone_il_mapping_bin_log' );

our @primary_key_names =
    qw/
      sp_clone_il_mapping_bin_log_id
      /;

our @column_names =
    qw/
      sp_clone_il_mapping_bin_log_id
      genotype_region_id
      sp_person_id
      clone_id
      is_current
      created
      chromosome
      notes
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
