package CXGN::CDBI::Auto::SGNPeople::CloneValidationLog;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::CloneValidationLog - object abstraction for rows in the sgn_people.clone_validation_log table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:


  Columns:
      clone_validation_log_id
      sp_person_id
      clone_id
      val_overgo
      val_bac_ends
      is_current
      created

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.clone_validation_log' );

our @primary_key_names =
    qw/

      /;

our @column_names =
    qw/
      clone_validation_log_id
      sp_person_id
      clone_id
      val_overgo
      val_bac_ends
      is_current
      created
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
