package CXGN::CDBI::Auto::SGNPeople::ForumTopic;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::ForumTopic - object abstraction for rows in the sgn_people.forum_topic table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      forum_topic_id

  Columns:
      forum_topic_id
      person_id
      topic_name
      parent_topic
      topic_class
      page_type
      page_object_id
      topic_description
      sort_order

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.forum_topic' );

our @primary_key_names =
    qw/
      forum_topic_id
      /;

our @column_names =
    qw/
      forum_topic_id
      person_id
      topic_name
      parent_topic
      topic_class
      page_type
      page_object_id
      topic_description
      sort_order
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
