package CXGN::CDBI::Auto::SGNPeople::ForumPost;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::ForumPost - object abstraction for rows in the sgn_people.forum_post table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      forum_post_id

  Columns:
      forum_post_id
      person_id
      post_text
      parent_post_id
      forum_topic_id
      subject
      post_time

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.forum_post' );

our @primary_key_names =
    qw/
      forum_post_id
      /;

our @column_names =
    qw/
      forum_post_id
      person_id
      post_text
      parent_post_id
      forum_topic_id
      subject
      post_time
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
