package CXGN::CDBI::Auto::SGNPeople::List;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::List - object abstraction for rows in the sgn_people.list table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      list_id

  Columns:
      list_id
      is_hotlist
      sent_by
      name
      description
      owner

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.list' );

our @primary_key_names =
    qw/
      list_id
      /;

our @column_names =
    qw/
      list_id
      is_hotlist
      sent_by
      name
      description
      owner
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
