package CXGN::CDBI::Auto::SGNPeople::ListItem;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::ListItem - object abstraction for rows in the sgn_people.list_item table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      list_item_id

  Columns:
      list_item_id
      content
      list_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.list_item' );

our @primary_key_names =
    qw/
      list_item_id
      /;

our @column_names =
    qw/
      list_item_id
      content
      list_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
