package CXGN::CDBI::Auto::SGNPeople::SpGroup;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::SpGroup - object abstraction for rows in the sgn_people.sp_group table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      sp_group_id

  Columns:
      sp_group_id
      name
      description

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.sp_group' );

our @primary_key_names =
    qw/
      sp_group_id
      /;

our @column_names =
    qw/
      sp_group_id
      name
      description
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
