package CXGN::CDBI::Auto::SGNPeople::SpLoginOld;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::SpLoginOld - object abstraction for rows in the sgn_people.sp_login_old table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      sp_login_id

  Columns:
      sp_login_id
      username
      private_email
      pending_email
      password
      confirm_code
      disabled
      user_type

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.sp_login_old' );

our @primary_key_names =
    qw/
      sp_login_id
      /;

our @column_names =
    qw/
      sp_login_id
      username
      private_email
      pending_email
      password
      confirm_code
      disabled
      user_type
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
