package CXGN::CDBI::Auto::SGNPeople::SpOrganisms;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::SpOrganisms - object abstraction for rows in the sgn_people.sp_organisms table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      organism_id

  Columns:
      organism_id
      organism_name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.sp_organisms' );

our @primary_key_names =
    qw/
      organism_id
      /;

our @column_names =
    qw/
      organism_id
      organism_name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
