package CXGN::CDBI::Auto::SGNPeople::SpOrganization;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::SpOrganization - object abstraction for rows in the sgn_people.sp_organization table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      sp_organization_id

  Columns:
      sp_organization_id
      name
      department
      unit
      address
      country
      phone_number
      fax
      contact_email
      webpage
      description
      upload_account_name
      shortname

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.sp_organization' );

our @primary_key_names =
    qw/
      sp_organization_id
      /;

our @column_names =
    qw/
      sp_organization_id
      name
      department
      unit
      address
      country
      phone_number
      fax
      contact_email
      webpage
      description
      upload_account_name
      shortname
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
