package CXGN::CDBI::Auto::SGNPeople::SpPerson;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::SpPerson - object abstraction for rows in the sgn_people.sp_person table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      sp_person_id

  Columns:
      sp_person_id
      censor
      salutation
      last_name
      first_name
      organization
      address
      country
      phone_number
      fax
      contact_email
      webpage
      research_keywords
      user_format
      research_interests
      formatted_interests
      contact_update
      research_update
      sp_login_id
      username
      private_email
      pending_email
      password
      confirm_code
      disabled
      user_type
      cookie_string
      last_access_time
      user_prefs
      developer_settings

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.sp_person' );

our @primary_key_names =
    qw/
      sp_person_id
      /;

our @column_names =
    qw/
      sp_person_id
      censor
      salutation
      last_name
      first_name
      organization
      address
      country
      phone_number
      fax
      contact_email
      webpage
      research_keywords
      user_format
      research_interests
      formatted_interests
      contact_update
      research_update
      sp_login_id
      username
      private_email
      pending_email
      password
      confirm_code
      disabled
      user_type
      cookie_string
      last_access_time
      user_prefs
      developer_settings
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
