package CXGN::CDBI::Auto::SGNPeople::UserMapData;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::SGNPeople::UserMapData - object abstraction for rows in the sgn_people.user_map_data table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      user_map_data_id

  Columns:
      user_map_data_id
      user_map_id
      marker_name
      protocol
      marker_id
      linkage_group
      position
      confidence
      sp_person_id
      obsolete
      modified_date
      create_date

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'sgn_people.user_map_data' );

our @primary_key_names =
    qw/
      user_map_data_id
      /;

our @column_names =
    qw/
      user_map_data_id
      user_map_id
      marker_name
      protocol
      marker_id
      linkage_group
      position
      confidence
      sp_person_id
      obsolete
      modified_date
      create_date
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
