package CXGN::CDBI::Auto::Phenome::AlleleAlias;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::AlleleAlias - object abstraction for rows in the phenome.allele_alias table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      allele_alias_id

  Columns:
      allele_alias_id
      alias
      allele_id
      preferred
      obsolete
      sp_person_id
      create_date
      modified_date

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.allele_alias' );

our @primary_key_names =
    qw/
      allele_alias_id
      /;

our @column_names =
    qw/
      allele_alias_id
      alias
      allele_id
      preferred
      obsolete
      sp_person_id
      create_date
      modified_date
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
