package CXGN::CDBI::Auto::Phenome::DbxrefType;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::DbxrefType - object abstraction for rows in the phenome.dbxref_type table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      dbxref_type_id

  Columns:
      dbxref_type_id
      dbxref_type_name
      dbxref_type_definition
      dbxref_type_url

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.dbxref_type' );

our @primary_key_names =
    qw/
      dbxref_type_id
      /;

our @column_names =
    qw/
      dbxref_type_id
      dbxref_type_name
      dbxref_type_definition
      dbxref_type_url
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
