package CXGN::CDBI::Auto::Phenome::GenotypeRegion;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

DEPRECATED. SGN no longer uses CDBI and this class does not reflect the database schema. Replaced by DBIx::Class. See CXGN::Phenome::Schema::GenotypeRegion

CXGN::CDBI::Auto::Phenome::GenotypeRegion - object abstraction for rows in the phenome.genotype_region table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      genotype_region_id

  Columns:
      genotype_region_id
      genotype_id
      marker_id_nn
      marker_id_ns
      marker_id_sn
      marker_id_ss
      zygocity_code
      lg_id
      type
      name
      sp_person_id
      modified_date
      create_date
      obsolete

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.genotype_region' );

our @primary_key_names =
    qw/
      genotype_region_id
      /;

our @column_names =
    qw/
      genotype_region_id
      genotype_id
      marker_id_nn
      marker_id_ns
      marker_id_sn
      marker_id_ss
      zygocity_code
      lg_id
      type
      name
      sp_person_id
      modified_date
      create_date
      obsolete
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
