package CXGN::CDBI::Auto::Phenome::Germplasm;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::Germplasm - object abstraction for rows in the phenome.germplasm table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      germplasm_id

  Columns:
      germplasm_id
      germplasm_type
      individual_id
      description
      dbxref_id
      sp_person_id
      create_date
      modified_date
      obsolete

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.germplasm' );

our @primary_key_names =
    qw/
      germplasm_id
      /;

our @column_names =
    qw/
      germplasm_id
      germplasm_type
      individual_id
      description
      dbxref_id
      sp_person_id
      create_date
      modified_date
      obsolete
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
