package CXGN::CDBI::Auto::Phenome::Image;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::Image - object abstraction for rows in the phenome.image table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      image_id

  Columns:
      image_id
      phenotype_id
      image_file_name

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.image' );

our @primary_key_names =
    qw/
      image_id
      /;

our @column_names =
    qw/
      image_id
      phenotype_id
      image_file_name
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
