package CXGN::CDBI::Auto::Phenome::IndividualHistory;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::IndividualHistory - object abstraction for rows in the phenome.individual_history table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      individual_history_id

  Columns:
      individual_history_id
      individual_id
      name
      description
      population_id
      sp_person_id
      updated_by
      obsolete
      create_date

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.individual_history' );

our @primary_key_names =
    qw/
      individual_history_id
      /;

our @column_names =
    qw/
      individual_history_id
      individual_id
      name
      description
      population_id
      sp_person_id
      updated_by
      obsolete
      create_date
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
