package CXGN::CDBI::Auto::Phenome::IndividualDbxrefEvidence;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::IndividualDbxrefEvidence - object abstraction for rows in the phenome.individual_dbxref_evidence table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      individual_dbxref_evidence_id

  Columns:
      individual_dbxref_evidence_id
      individual_dbxref_id
      relationship_type
      evidence_code
      evidence_description
      evidence_with
      reference_id
      sp_person_id
      updated_by
      create_date
      modified_date
      obsolete

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.individual_dbxref_evidence' );

our @primary_key_names =
    qw/
      individual_dbxref_evidence_id
      /;

our @column_names =
    qw/
      individual_dbxref_evidence_id
      individual_dbxref_id
      relationship_type
      evidence_code
      evidence_description
      evidence_with
      reference_id
      sp_person_id
      updated_by
      create_date
      modified_date
      obsolete
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
