package CXGN::CDBI::Auto::Phenome::LocusDbxrefEvidenceHistory;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::LocusDbxrefEvidenceHistory - object abstraction for rows in the phenome.locus_dbxref_evidence_history table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      locus_dbxref_evidence_history_id

  Columns:
      locus_dbxref_evidence_history_id
      locus_dbxref_evidence_id
      locus_dbxref_id
      relationship_type
      evidence_code
      evidence_description
      evidence_with
      reference_id
      sp_person_id
      updated_by
      create_date
      modified_date
      obsolete

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.locus_dbxref_evidence_history' );

our @primary_key_names =
    qw/
      locus_dbxref_evidence_history_id
      /;

our @column_names =
    qw/
      locus_dbxref_evidence_history_id
      locus_dbxref_evidence_id
      locus_dbxref_id
      relationship_type
      evidence_code
      evidence_description
      evidence_with
      reference_id
      sp_person_id
      updated_by
      create_date
      modified_date
      obsolete
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
