package CXGN::CDBI::Auto::Phenome::Locus2locus;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::Locus2locus - object abstraction for rows in the phenome.locus2locus table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      locus2locus_id

  Columns:
      locus2locus_id
      subject_id
      object_id
      relationship_id
      evidence_id
      reference_id
      sp_person_id
      obsolete
      modified_date
      create_date

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.locus2locus' );

our @primary_key_names =
    qw/
      locus2locus_id
      /;

our @column_names =
    qw/
      locus2locus_id
      subject_id
      object_id
      relationship_id
      evidence_id
      reference_id
      sp_person_id
      obsolete
      modified_date
      create_date
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
