package CXGN::CDBI::Auto::Phenome::Phenotype;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::Phenotype - object abstraction for rows in the phenome.phenotype table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      phenotype_id

  Columns:
      phenotype_id
      population_id
      allele_id
      locus_id
      allele_type
      verified_allele
      phenotype_accession
      phenotype_type
      phenotype_details

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.phenotype' );

our @primary_key_names =
    qw/
      phenotype_id
      /;

our @column_names =
    qw/
      phenotype_id
      population_id
      allele_id
      locus_id
      allele_type
      verified_allele
      phenotype_accession
      phenotype_type
      phenotype_details
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
