package CXGN::CDBI::Auto::Phenome::PhenotypeTerm;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::PhenotypeTerm - object abstraction for rows in the phenome.phenotype_term table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      phenotype_term_id

  Columns:
      phenotype_term_id
      term_ref
      term_id
      phenotype_id

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.phenotype_term' );

our @primary_key_names =
    qw/
      phenotype_term_id
      /;

our @column_names =
    qw/
      phenotype_term_id
      term_ref
      term_id
      phenotype_id
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
