package CXGN::CDBI::Auto::Phenome::PolymorphicFragment;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

DEPRECATED. SGN no longer uses CDBI and this class does not reflect the database schema. Replaced by DBIx::Class. See CXGN::Phenome::Schema::PolymorphicFragment

CXGN::CDBI::Auto::Phenome::PolymorphicFragment - object abstraction for rows in the phenome.polymorphic_fragment table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      polymorphic_fragment_id

  Columns:
      polymorphic_fragment_id
      genotype_id
      flanking_marker1_id
      flanking_marker2_id
      zygocity
      linkage_group
      type
      sp_person_id
      modified_date
      create_date
      obsolete

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.polymorphic_fragment' );

our @primary_key_names =
    qw/
      polymorphic_fragment_id
      /;

our @column_names =
    qw/
      polymorphic_fragment_id
      genotype_id
      flanking_marker1_id
      flanking_marker2_id
      zygocity
      linkage_group
      type
      sp_person_id
      modified_date
      create_date
      obsolete
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
