package CXGN::CDBI::Auto::Phenome::Population;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::Population - object abstraction for rows in the phenome.population table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      population_id

  Columns:
      population_id
      name
      description
      person_id
      sp_person_id
      create_date
      modified_date
      background_accession_id
      obsolete

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.population' );

our @primary_key_names =
    qw/
      population_id
      /;

our @column_names =
    qw/
      population_id
      name
      description
      person_id
      sp_person_id
      create_date
      modified_date
      background_accession_id
      obsolete
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
