package CXGN::CDBI::Auto::Phenome::Registry;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::Registry - object abstraction for rows in the phenome.registry table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      registry_id

  Columns:
      registry_id
      symbol
      name
      description
      origin
      sp_person_id
      updated_by
      create_date
      modified_date
      status

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.registry' );

our @primary_key_names =
    qw/
      registry_id
      /;

our @column_names =
    qw/
      registry_id
      symbol
      name
      description
      origin
      sp_person_id
      updated_by
      create_date
      modified_date
      status
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
