package CXGN::CDBI::Auto::Phenome::TomatoIlBin;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::TomatoIlBin - object abstraction for rows in the phenome.tomato_il_bin table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      il_bin_id

  Columns:
      il_bin_id
      chromosome
      name
      n_marker_n
      n_marker_s
      s_marker_n
      s_marker_s

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.tomato_il_bin' );

our @primary_key_names =
    qw/
      il_bin_id
      /;

our @column_names =
    qw/
      il_bin_id
      chromosome
      name
      n_marker_n
      n_marker_s
      s_marker_n
      s_marker_s
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
