package CXGN::CDBI::Auto::Phenome::TomatoTerm;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::TomatoTerm - object abstraction for rows in the phenome.tomato_term table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      tomato_term_id

  Columns:
      tomato_term_id
      tomato_term_name
      tomato_term_type
      tomato_term_acc
      is_obsolete
      is_root

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.tomato_term' );

our @primary_key_names =
    qw/
      tomato_term_id
      /;

our @column_names =
    qw/
      tomato_term_id
      tomato_term_name
      tomato_term_type
      tomato_term_acc
      is_obsolete
      is_root
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
