package CXGN::CDBI::Auto::Phenome::TomatoTerm2term;
# This class is autogenerated by cdbigen.pl.  Any modification
# by you will be fruitless.

=head1 DESCRIPTION

CXGN::CDBI::Auto::Phenome::TomatoTerm2term - object abstraction for rows in the phenome.tomato_term2term table.

Autogenerated by cdbigen.pl.

=head1 DATA FIELDS

  Primary Keys:
      tomato_term2term_id

  Columns:
      tomato_term2term_id
      relationship_type_id
      term1_id
      term2_id
      complete

  Sequence:
      none

=cut

use base 'CXGN::CDBI::Class::DBI';
__PACKAGE__->table( 'phenome.tomato_term2term' );

our @primary_key_names =
    qw/
      tomato_term2term_id
      /;

our @column_names =
    qw/
      tomato_term2term_id
      relationship_type_id
      term1_id
      term2_id
      complete
      /;

__PACKAGE__->columns( Primary => @primary_key_names, );
__PACKAGE__->columns( All     => @column_names,      );


=head1 AUTHOR

cdbigen.pl

=cut

###
1;#do not remove
###
